// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BookingStatus = "inquiry" | "pending_approval" | "confirmed" | "active" | "delivered" | "completed" | "declined" | "cancelled" | "refunded";
