// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CalendarOverride = { id: string, creator_id: string, start_datetime: string, end_datetime: string, reason: string | null, is_full_day: boolean, };
