// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChatMessage = { id: string, sender_id: string, receiver_id: string, text: string, timestamp: string, };
