// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatePackageItem } from "./CreatePackageItem";

export type CreatorOnboardPayload = { name: string, handle: string | null, bio: string, discipline: string, sub_skills: Array<string>, years_exp: number, city: string, languages: Array<string>, travel_mode: string, upi_id: string, instagram_handle: string, youtube_handle: string | null, website_url: string | null, portfolio_urls: Array<string>, packages: Array<CreatePackageItem>, };
