// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreatorCalendarSettings = { creator_id: string, slot_step_minutes: number, buffer_minutes: number, min_notice_hours: number, holiday_mode: boolean, calendar_token: string, };
