// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreatorFilterParams = { discipline: string | null, city: string | null, min_price: number | null, max_price: number | null, min_rating: number | null, available_today: boolean | null, target_date: string | null, duration_minutes: number | null, sort: string | null, };
