// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreatePackageItem = { name: string, price: number, duration: string, inclusions: Array<string>, delivery_days: number | null, };
