// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CustomQuote = { id: string, creator_id: string, client_id: string, scope: string, price: number, delivery: string, note: string | null, status: string, created_at: string, };
