// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DayAvailability = { date: string, status: string, slots: Array<string>, reason: string | null, is_custom_hours: boolean | null, custom_start_time: string | null, custom_end_time: string | null, };
