// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DisciplineFilterOption = { id: string, name: string, icon: string, sub_skills: Array<string>, default_step_minutes: number, default_buffer_minutes: number, };
