// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Discipline = "photography" | "videography" | "styling" | "makeup_hair" | "creative_direction" | "podcast_studio" | "post_production";
