// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EscrowStatus = "held_in_escrow" | "released_to_creator" | "refunded_to_client" | "disputed";
