// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisciplineFilterOption } from "./DisciplineFilterOption";
import type { PriceRangeConfig } from "./PriceRangeConfig";
import type { SortOption } from "./SortOption";

export type FilterConfig = { disciplines: Array<DisciplineFilterOption>, cities: Array<string>, price_range: PriceRangeConfig, sort_options: Array<SortOption>, ratings: Array<number>, };
