// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DayAvailability } from "./DayAvailability";

export type MonthAvailabilityResponse = { creator_id: string, month: string, duration_minutes: number, slot_step_minutes: number, buffer_minutes: number, holiday_mode: boolean, days: { [key: string]: DayAvailability }, };
