// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PayoutBalance = { available_balance: number, pending_escrow: number, total_earned: number, upi_id: string, };
