// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisciplineFilterOption } from "./DisciplineFilterOption";
import type { PriceRangeConfig } from "./PriceRangeConfig";
import type { SortOption } from "./SortOption";

export type PlatformConfig = { sla_hours: bigint, default_advance_pct: number, default_platform_fee_pct: number, default_slot_step_minutes: number, default_buffer_minutes: number, default_min_notice_hours: number, cities: Array<string>, disciplines: Array<DisciplineFilterOption>, price_range: PriceRangeConfig, sort_options: Array<SortOption>, };
