// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PriceRangeConfig = { min: number, max: number, step: number, default_min: number, default_max: number, };
