// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Transaction = { id: string, amount: number, transaction_type: string, status: string, description: string, created_at: string, };
