// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateScheduleItem = { day_of_week: number, is_active: boolean, start_time: string, end_time: string, };
