// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateScheduleItem } from "./UpdateScheduleItem";

export type UpdateCalendarSettingsPayload = { slot_step_minutes: number | null, buffer_minutes: number | null, min_notice_hours: number | null, holiday_mode: boolean | null, schedules: Array<UpdateScheduleItem> | null, };
