// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type User = { id: string, phone: string, name: string, role: string, city: string | null, handle: string | null, trust_score: number, is_creator: boolean, };
