// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateQuotePayload = { client_id: string, scope: string, price: number, delivery: string, note: string | null, };
